language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - nightly
env:
  - RUSTFLAGS="-D warnings"
os:
  - linux
  - osx
branches:
  only:
    - master
    - dev
script:
  - cargo build -v --lib --no-default-features
  - cargo build -v --bins
  - cargo test --no-default-features --lib
  - cargo test --doc --no-default-features
  - cargo doc --no-deps
